alias bstart='systemctl --user start boomer.service'
alias bstop='systemctl --user stop boomer.service'
alias uistop='systemctl --user stop base_gui.service'
alias bstat='systemctl --user status boomer.service'
alias blog='tail -f /run/shm/boomer.log'
alias clog='rm /run/shm/boomer.log'
alias scap='function _scap(){ sudo setcap "cap_sys_nice=eip" $1; };_scap'
alias bps='ps -e | grep -E --color=none cam\|base'
alias bsync='scp /home/pi/boomer/staged/b*.out pi@base:/home/pi/boomer/staged'
alias basesync='scp /home/pi/boomer/staged/base*.out pi@base:/home/pi/boomer/staged'
alias bcamsync='scp /home/pi/boomer/staged/bcam*.out pi@base:/home/pi/boomer/staged'

alias bclean='rm -v build/CMakeFiles/*/*.o'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias pulse16='sudo sh -c '\''cd /sys/class/pwm/pwmchip0; echo 0 > export; cd pwm0; echo 16688200 > period; echo 8000000 > duty_cycle; echo 1 > enable'\'''
alias pulse21='sudo sh -c '\''cd /sys/class/pwm/pwmchip0; echo 0 > export; cd pwm0; echo 21000000 > period; echo 8000000 > duty_cycle; echo 1 > enable'\'''
